INSERT INTO CATEGORY ( CATEGORY) VALUES ('Food');
INSERT INTO CATEGORY ( CATEGORY) VALUES ('Toys');
INSERT INTO CATEGORY ( CATEGORY) VALUES ('Tools');
INSERT INTO CATEGORY ( CATEGORY) VALUES ('Alcohol');
INSERT INTO CATEGORY ( CATEGORY) VALUES ('Drugs');
